workspace:
  base: /srv/app
clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: false

pipeline:
  frontend:
      image: webhippie/nodejs:latest
      pull: true
      commands:
          - npm install
          - npm test
      when:
          event: [ push, pull_request ]
  discord:
      image: appleboy/drone-discord
      pull: true
      secrets: [ discord_webhook_id, discord_webhook_token ]
      message: |
        {{ #success build.status }}
            build {{ build.number }} succeeded. Good job.
        {{ else }}
            build {{ build.number }} failed. Fix me please.
        {{ /success }}
      when:
        status: [ success, failure ]
